name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
      - production
jobs:
  Deploy-Production:
    runs-on:
      labels: ubuntu-22.04-2cpu-8ram-75ssd
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy on Vercel
        id: deploy
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}